// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
  if (kIsWeb) {
    return web;
  }
  switch (defaultTargetPlatform) {
    case TargetPlatform.android:
      return android;
    case TargetPlatform.iOS:
      return ios;
    case TargetPlatform.macOS:
    case TargetPlatform.windows:
    case TargetPlatform.linux:
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for this platform.',
      );
    default:
      throw UnsupportedError(
        'DefaultFirebaseOptions are not supported for this platform.',
      );
  }
}

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmY5MvWWb1JFvj6RAFvCcjQmMyBo-JGzk',
    appId: '1:628835043847:android:09107a42f7728f7ca8b8a2',
    messagingSenderId: '628835043847',
    projectId: 'souzacomercio-e036b',
    storageBucket: 'souzacomercio-e036b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFk9DzTBSjpNObFHISjSzMR_6yizQchDE',
    appId: '1:628835043847:ios:c86a9b89f53ab3a6a8b8a2',
    messagingSenderId: '628835043847',
    projectId: 'souzacomercio-e036b',
    storageBucket: 'souzacomercio-e036b.firebasestorage.app',
    iosBundleId: 'com.example.emprestimosApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfloR7vi5_8pMoR8jHZt5XFgxc-ZgtYaY',
    appId: '1:628835043847:web:b0576c4d1bce4350a8b8a2',
    messagingSenderId: '628835043847',
    projectId: 'souzacomercio-e036b',
    authDomain: 'souzacomercio-e036b.firebaseapp.com',
    storageBucket: 'souzacomercio-e036b.firebasestorage.app',
    measurementId: 'G-NP71V3FHZH',
  );

}